/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examsBaseService PLEASE EDIT ../exams.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exams } from '../../domain/zuct_db/exams';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../exams.service.ts
 */

/*
 * SCHEMA DB exams
 *
	{
		place: {
			type: 'String'
		},
		score: {
			type: 'Number'
		},
		valid: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_courses: {
			type: Schema.ObjectId,
			ref : "exams"
		},
		_lecturer: {
			type: Schema.ObjectId,
			ref : "exams"
		},
		_students: {
			type: Schema.ObjectId,
			ref : "exams"
		},
	}
 *
 */
@Injectable()
export class ExamsBaseService {

    contextUrl: string = environment.endpoint + '/exams';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * examsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exams): Observable<Exams> {
        return this.http
            .post<Exams>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * examsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * examsService.findBy_courses
    *   @description CRUD ACTION findBy_courses
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_courses(id: string): Observable<Exams[]> {
        return this.http
            .get<Exams[]>(this.contextUrl + '/findBy_courses/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examsService.findBy_lecturer
    *   @description CRUD ACTION findBy_lecturer
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_lecturer(id: string): Observable<Exams[]> {
        return this.http
            .get<Exams[]>(this.contextUrl + '/findBy_lecturer/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examsService.findBy_students
    *   @description CRUD ACTION findBy_students
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_students(id: string): Observable<Exams[]> {
        return this.http
            .get<Exams[]>(this.contextUrl + '/findBy_students/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * examsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Exams> {
        return this.http
            .get<Exams>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * examsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exams[]> {
        return this.http
            .get<Exams[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * examsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Exams): Observable<Exams> {
        return this.http
            .post<Exams>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs


    /**
    * examsService.validate
    *   @description This API is used to validate the exam
    *   @param String id is of the exam
    *   @returns Boolean
    *
    */
    validate(...params: any[]): Observable<any> {
        return this.http
            .post<any>(this.contextUrl + '/{id}/validate', {})
            .pipe(
                map(response => response)
            );
    }

}
