/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE examsBase PLEASE EDIT ../exams.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Courses } from '../courses';
import { Lecturers } from '../lecturers';
import { Students } from '../students';

/**
 * This is the model of exams object
 *
 */
export class ExamsBase {

    constructor() { }

    public _id: string;
    public place?: string;
    public score?: number;
    public valid?: Boolean;
    // Relations _courses
    public _courses: Courses | string;
    // Relations _lecturer
    public _lecturer: Lecturers | string;
    // Relations _students
    public _students: Students | string;
}
